version: "3.9"
services:
  db:
    image: postgres:latest
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=kissa123
    hostname: db
    domainname: localhost
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432